### ISSUE TITLE
Cannot find module './config/userConfiguration'

### ISSUE THREAD

**Issue by shivkanthbuddha** [lucasriondel/gmail-attachments-downloader#1]
Hi first of all thanks for the i am getting the issue when i am trying to run the application 

1) downloaded the zip 
2) executed the below commands 
npm install
npm install -g typescript
tsc

3) getting the below error

 src/index.ts:12:27 - error TS2307: Cannot find module './config/userConfiguration'.

12 import configuration from './config/userConfiguration';
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by lucasriondel** [comment]
@shivkanthbuddha sorry for the wait. It's not an issue, you have to create that file according to the readme. It was unclear so I've updated it. You should be able to run the script once this file is on your hard drive.

**Comment by daledali** [comment]
yours says src/userConfiguration.ts
should it be ./config/userConfiguration ?

**Comment by lucasriondel** [comment]
@daledali if you look at this file, it should be `src/config/configuration.ts` https://github.com/lucasriondel/gmail-attachments-downloader/blob/master/src/config/configuration.ts

**Comment by lucasriondel** [comment]
I'm closing the issue.
